
#ifndef INC_RCC_H_
#define INC_RCC_H_
#include "stm32f303xx.h"


/*
 * RCC_CR Register Macros
 *
 */

#define RCC_CR_HSI_ENABLE()        SET_BIT(RCC->CR,RCC_CR_HSIEN)
#define RCC_CR_HSI_DISABLE()       CLEAR_BIT(RCC->CR,RCC_CR_HSIEN)
#define RCC_CR_HSI_READ()          do{uint32_t tempReg=0;                            \
                                       tempReg=READ_BIT(RCC->CR,RCC_CR_HSIRDY_Pos);    \
                                       UNUSED(tempReg);                                \
                                        }while(0)

#define RCC_CR_HSE_ENABLE()         SET_BIT(RCC->CR,RCC_CR_HSEEN)
#define RCC_CR_HSE_DISABLE()        CLEAR_BIT(RCC->CR,RCC_CR_HSEEN)
#define RCC_CR_HSE_FLAG             (RCC->CR & (0x1<<RCC_CR_HSERDY_Pos))


#define RCC_CR_HSEBYP_ENABLE()      SET_BIT(RCC->CR,RCC_CR_HSEBYPEN)
#define RCC_CR_HSEBYP_DISABLE()     CLEAR_BIT(RCC->CR,RCC_CR_HSEBYPEN)
#define RCC_CR_HSEBYP_READ()        do{uint32_t tempReg=0;                           \
                                         tempReg=READ_BIT(RCC->CR,RCC_CR_HSEBYPEN);    \
                                         UNUSED(tempReg);                              \
                                         }while(0)

#define RCC_CR_CSS_ENABLE()         SET_BIT(RCC->CR,RCC_CR_CSSEN)
#define RCC_CR_CSS_DISABLE()        CLEAR_BIT(RCC->CR,RCC_CR_CSSEN)
#define RCC_CR_CSS_READ()           do{uint32_t tempReg=0;                           \
                                         tempReg=READ_BIT(RCC->CR,RCC_CR_CSSEN);       \
                                         UNUSED(tempReg);                              \
                                         }while(0)

#define RCC_CR_PLL_ENABLE()         SET_BIT(RCC->CR,RCC_CR_PLLEN)
#define RCC_CR_PLL_DISABLE()        CLEAR_BIT(RCC->CR,RCC_CR_PLLEN)
#define RCC_CR_PLL_FLAG             (RCC->CR & (0x1<<RCC_CR_PLLRDY_Pos))

/*
 * @def_group RCC_CFGR_SW
 *
 */

#define RCC_CFGR_HSI                      (0x00U)
#define RCC_CFGR_HSE                      (0x01U)
#define RCC_CFGR_PLL                      (0x02U)

/*
 * @def_group RCC_CFGR_SWS
 *
 */

#define RCC_CFGR_SWS_HSI                  (0x00U)
#define RCC_CFGR_SWS_HSE                  (0x01U)
#define RCC_CFGR_SWS_PLL                  (0x02U)

/*
 * @def_group RCC_CFGR_HPRE
 *
 */

#define RCC_CFGR_HLCK_PRE_1               (0x00U)
#define RCC_CFGR_HLCK_PRE_2               (0x08U)
#define RCC_CFGR_HLCK_PRE_4               (0x09U)
#define RCC_CFGR_HLCK_PRE_8               (0x0AU)
#define RCC_CFGR_HLCK_PRE_16              (0x0BU)
#define RCC_CFGR_HLCK_PRE_64              (0x0CU)
#define RCC_CFGR_HLCK_PRE_128             (0x0DU)
#define RCC_CFGR_HLCK_PRE_256             (0x0EU)
#define RCC_CFGR_HLCK_PRE_512             (0x0FU)

/*
 * @def_group RCC_CFGR_PPRE1
 *
 */

#define RCC_CFGR_APB1_PRE_1               (0x00U)
#define RCC_CFGR_APB1_PRE_2               (0x04U)
#define RCC_CFGR_APB1_PRE_4               (0x05U)
#define RCC_CFGR_APB1_PRE_8               (0x06U)
#define RCC_CFGR_APB1_PRE_16              (0x07U)

/*
 * @def_group RCC_CFGR_PPRE2
 *
 */

#define RCC_CFGR_APB2_PRE_1               (0x00U)
#define RCC_CFGR_APB2_PRE_2               (0x04U)
#define RCC_CFGR_APB2_PRE_4               (0x05U)
#define RCC_CFGR_APB2_PRE_8               (0x06U)
#define RCC_CFGR_APB2_PRE_16              (0x07U)

/*
 * @def_group RCC_CFGR_PLLSRC
 *
 */

#define RCC_CFGR_PLLSRC_HSI               (0x00U)
#define RCC_CFGR_PLLRSRC_HSE              (0x01U)

/*
 * @def_group RCC_CFGR_PLLXTPRE
 *
 */

#define RCC_CFGR_PLLXTPRE_NODIV           (0x00U)
#define RCC_CFGR_PLLXLTPRE_DIV            (0x01U)

/*
 * @def_group RCC_CFGR_PLLMUL
 *
 */

#define RCC_CFGR_PLLMUL_2                 (0x00U)
#define RCC_CFGR_PLLMUL_3                 (0x01U)
#define RCC_CFGR_PLLMUL_4                 (0x02U)
#define RCC_CFGR_PLLMUL_5                 (0x03U)
#define RCC_CFGR_PLLMUL_6                 (0x04U)
#define RCC_CFGR_PLLMUL_7                 (0x05U)
#define RCC_CFGR_PLLMUL_8                 (0x06U)
#define RCC_CFGR_PLLMUL_9                 (0x07U)
#define RCC_CFGR_PLLMUL_10                (0x08U)
#define RCC_CFGR_PLLMUL_11                (0x09U)
#define RCC_CFGR_PLLMUL_12                (0x0AU)
#define RCC_CFGR_PLLMUL_13                (0x0BU)
#define RCC_CFGR_PLLMUL_14                (0x0CU)
#define RCC_CFGR_PLLMUL_15                (0x0DU)
#define RCC_CFGR_PLLMUL_16                (0x0EU)

/*
 * @def_group RCC_CFGR_USBPRE
 *
 */

#define RCC_CFGR_USBPRE_DIV               (0x00U)
#define RCC_CFGR_USBPRE_NODIV             (0x01U)

/*
 * @def_group RCC_CFGR_I2SSRC
 *
 */

#define RCC_CFGR_I2SSRC_SYSCLK            (0x00U)
#define RCC_CFGR_USBPRE_EXCLK             (0x01U)

/*
 * @def_group RCC_CFGR_MCO
 *
 */

#define RCC_CFGR_MCO_DISABLED             (0x00U)
#define RCC_CFGR_MCO_LSI                  (0x02U)
#define RCC_CFGR_MCO_LSE                  (0x03U)
#define RCC_CFGR_MCO_SYSCLK               (0x04U)
#define RCC_CFGR_MCO_HSI                  (0x05U)
#define RCC_CFGR_MCO_HSE                  (0x06U)
#define RCC_CFGR_MCO_PLL                  (0x07U)


/*
 * RCC_CFGR Register Macros
 *
 */


#define RCC_CFGR_SW_HSI_ENABLE()           SET_BIT(RCC->CFGR,RCC_CFGR_SW__HSIEN)
#define RCC_CFGR_SW_HSE_ENABLE()           SET_BIT(RCC->CFGR,RCC_CFGR_SW__HSEEN)
#define RCC_CFGR_SW_PLL_ENABLE()           SET_BIT(RCC->CFGR,RCC_CFGR_SW__PLLEN)

#define RCC_CFGR_HPRE_DIV1_ENABLE()        SET_BIT(RCC->CFGR,RCC_CFGR_HPRE_PRE1EN)
#define RCC_CFGR_HPRE_DIV2_ENABLE()        SET_BIT(RCC->CFGR,RCC_CFGR_HPRE_PRE2EN)
#define RCC_CFGR_HPRE_DIV4_ENABLE()        SET_BIT(RCC->CFGR,RCC_CFGR_HPRE_PRE4EN)
#define RCC_CFGR_HPRE_DIV8_ENABLE()        SET_BIT(RCC->CFGR,RCC_CFGR_HPRE_PRE8EN)
#define RCC_CFGR_HPRE_DIV16_ENABLE()       SET_BIT(RCC->CFGR,RCC_CFGR_HPRE_PRE16EN)
#define RCC_CFGR_HPRE_DIV64_ENABLE()       SET_BIT(RCC->CFGR,RCC_CFGR_HPRE_PRE64EN)
#define RCC_CFGR_HPRE_DIV128_ENABLE()      SET_BIT(RCC->CFGR,RCC_CFGR_HPRE_PRE128EN)
#define RCC_CFGR_HPRE_DIV256_ENABLE()      SET_BIT(RCC->CFGR,RCC_CFGR_HPRE_PRE256EN)
#define RCC_CFGR_HPRE_DIV512_ENABLE()      SET_BIT(RCC->CFGR,RCC_CFGR_HPRE_PRE512EN)

#define RCC_CFGR_PPRE1_DIV1_ENABLE()       SET_BIT(RCC->CFGR,RCC_CFGR_PPRE1_PRE1EN)
#define RCC_CFGR_PPRE1_DIV2_ENABLE()       SET_BIT(RCC->CFGR,RCC_CFGR_PPRE1_PRE2EN)
#define RCC_CFGR_PPRE1_DIV4_ENABLE()       SET_BIT(RCC->CFGR,RCC_CFGR_PPRE1_PRE4EN)
#define RCC_CFGR_PPRE1_DIV8_ENABLE()       SET_BIT(RCC->CFGR,RCC_CFGR_PPRE1_PRE8EN)
#define RCC_CFGR_PPRE1_DIV16_ENABLE()      SET_BIT(RCC->CFGR,RCC_CFGR_PPRE1_PRE16EN)

#define RCC_CFGR_PPRE2_DIV1_ENABLE()       SET_BIT(RCC->CFGR,RCC_CFGR_PPRE2_PRE1EN)
#define RCC_CFGR_PPRE2_DIV2_ENABLE()       SET_BIT(RCC->CFGR,RCC_CFGR_PPRE2_PRE2EN)
#define RCC_CFGR_PPRE2_DIV4_ENABLE()       SET_BIT(RCC->CFGR,RCC_CFGR_PPRE2_PRE4EN)
#define RCC_CFGR_PPRE2_DIV8_ENABLE()       SET_BIT(RCC->CFGR,RCC_CFGR_PPRE2_PRE8EN)
#define RCC_CFGR_PPRE2_DIV16_ENABLE()      SET_BIT(RCC->CFGR,RCC_CFGR_PPRE2_PRE16EN)

#define RCC_CFGR_PLLSRC_HSE_ENABLE()       SET_BIT(RCC->CFGR,RCC_CFGR_PLLSRC_HSEEN)
#define RCC_CFGR_PLLSRC_HSI_ENABLE()       SET_BIT(RCC->CFGR,RCC_CFGR_PLLSRC_HSIEN)

#define RCC_CFGR_PLLXPTR_NODIV_ENABLE()    SET_BIT(RCC->CFGR,RCC_CFGR_PLLXLPTR_NODIVEN)
#define RCC_CFGR_PLLXPTR_DIV_ENABLE()      SET_BIT(RCC->CFGR,RCC_CFGR_PLLXLPTR_DIVEN)

#define RCC_CFGR_PLLMUL_MUL2_ENABLE()      SET_BIT(RCC->CFGR,RCC_CFGR_PLLMUL2EN)
#define RCC_CFGR_PLLMUL_MUL3_ENABLE()      SET_BIT(RCC->CFGR,RCC_CFGR_PLLMUL3EN)
#define RCC_CFGR_PLLMUL_MUL4_ENABLE()      SET_BIT(RCC->CFGR,RCC_CFGR_PLLMUL4EN)
#define RCC_CFGR_PLLMUL_MUL5_ENABLE()      SET_BIT(RCC->CFGR,RCC_CFGR_PLLMUL5EN)
#define RCC_CFGR_PLLMUL_MUL6_ENABLE()      SET_BIT(RCC->CFGR,RCC_CFGR_PLLMUL6EN)
#define RCC_CFGR_PLLMUL_MUL7_ENABLE()      SET_BIT(RCC->CFGR,RCC_CFGR_PLLMUL7EN)
#define RCC_CFGR_PLLMUL_MUL8_ENABLE()      SET_BIT(RCC->CFGR,RCC_CFGR_PLLMUL8EN)
#define RCC_CFGR_PLLMUL_MUL9_ENABLE()      SET_BIT(RCC->CFGR,RCC_CFGR_PLLMUL9EN)
#define RCC_CFGR_PLLMUL_MUL10_ENABLE()     SET_BIT(RCC->CFGR,RCC_CFGR_PLLMUL10EN)
#define RCC_CFGR_PLLMUL_MUL11_ENABLE()     SET_BIT(RCC->CFGR,RCC_CFGR_PLLMUL11EN)
#define RCC_CFGR_PLLMUL_MUL12_ENABLE()     SET_BIT(RCC->CFGR,RCC_CFGR_PLLMUL12EN)
#define RCC_CFGR_PLLMUL_MUL13_ENABLE()     SET_BIT(RCC->CFGR,RCC_CFGR_PLLMUL13EN)
#define RCC_CFGR_PLLMUL_MUL14_ENABLE()     SET_BIT(RCC->CFGR,RCC_CFGR_PLLMUL14EN)
#define RCC_CFGR_PLLMUL_MUL15_ENABLE()     SET_BIT(RCC->CFGR,RCC_CFGR_PLLMUL15EN)
#define RCC_CFGR_PLLMUL_MUL16_ENABLE()     SET_BIT(RCC->CFGR,RCC_CFGR_PLLMUL16EN)

#define RCC_CFGR_USBPRE_DIV_ENABLE()       SET_BIT(RCC->CFGR,RCC_CFGR_USBPRE_DIVEN)
#define RCC_CFGR_USBPRE_NODIV_ENABLE()     SET_BIT(RCC->CFGR,RCC_CFGR_USBPRE_NODIVEN)

#define RCC_CFGR_I2SSRC_SYSCLK_ENABLE()    SET_BIT(RCC->CFGR,RCC_CFGR_I2SSRC_SYSCLKEN)
#define RCC_CFGR_I2SSRC_EXCLK_ENABLE()     SET_BIT(RCC->CFGR,RCC_CFGR_I2SSRC_EXCLKEN)

#define RCC_CFGR_MCO_DISABLED_ENABLE()     SET_BIT(RCC->CFGR,RCC_CFGR_MCO_DISABLEDEN)
#define RCC_CFGR_MCO_LSI_ENABLE()          SET_BIT(RCC->CFGR,RCC_CFGR_MCO_LSIEN)
#define RCC_CFGR_MCO_LSE_ENABLE()          SET_BIT(RCC->CFGR,RCC_CFGR_MCO_LSEEN)
#define RCC_CFGR_MCO_SYSCLK_ENABLE()       SET_BIT(RCC->CFGR,RCC_CFGR_MCO_SYSCLKEN)
#define RCC_CFGR_MCO_HSI_ENABLE()          SET_BIT(RCC->CFGR,RCC_CFGR_MCO_HSIEN)
#define RCC_CFGR_MCO_HSE_ENABLE()          SET_BIT(RCC->CFGR,RCC_CFGR_MCO_HSEEN)
#define RCC_CFGR_MCO_PLL_ENABLE()          SET_BIT(RCC->CFGR,RCC_CFGR_MCO_PLLEN)

#define RCC_CR_MCOF_FLAG                   (RCC->CFGR & 0x1<<RCC_CFGR_MCOF_Pos)


/*
 * RCC_CIR Register Macros
 *
 */

#define RCC_CIR_LSIRDYIE_ENABLE()          SET_BIT(RCC->CIR,RCC_CIR_LSIRDYIEEN)
#define RCC_CIR_LSERDYIE_ENABLE()          SET_BIT(RCC->CIR,RCC_CIR_LSERDYIEEN)
#define RCC_CIR_HSIRDYIE_ENABLE()          SET_BIT(RCC->CIR,RCC_CIR_HSIRDYIEEN)
#define RCC_CIR_HSERDYIE_ENABLE()          SET_BIT(RCC->CIR,RCC_CIR_HSERDYIEEN)
#define RCC_CIR_PLLRDYIE_ENABLE()          SET_BIT(RCC->CIR,RCC_CIR_PLLRDYIEEN)

#define RCC_CIR_LSIRDYC_CLEAR()            SET_BIT(RCC->CIR,RCC_CIR_LSIRDYCEN)
#define RCC_CIR_LSERDYC_CLEAR()            SET_BIT(RCC->CIR,RCC_CIR_LSERDYCEN)
#define RCC_CIR_HSIRDYC_CLEAR()            SET_BIT(RCC->CIR,RCC_CIR_HSIRDYCEN)
#define RCC_CIR_HSERDYC_CLEAR()            SET_BIT(RCC->CIR,RCC_CIR_HSERDYCEN)
#define RCC_CIR_PLLRDYC_CLEAR()            SET_BIT(RCC->CIR,RCC_CIR_PLLRDYCEN)
#define RCC_CIR_CSSC_CLEAR()               SET_BIT(RCC->CIR,RCC_CIR_CSSCEN)


/*
 * RCC_APB2STR Register Macros
 *
 */


#define RCC_APB2STR_SYSCFGR_RESET()        SET_BIT(RCC->APB2RSTR,RCC_APB2STR_SYSCFGSTREN)
#define RCC_APB2STR_TIM1_RESET()           SET_BIT(RCC->APB2RSTR,RCC_APB2STR_TIM1STREN)
#define RCC_APB2STR_SPI1_RESET()           SET_BIT(RCC->APB2RSTR,RCC_APB2STR_SPI1STREN)
#define RCC_APB2STR_TIM8_RESET()           SET_BIT(RCC->APB2RSTR,RCC_APB2STR_TIM8STREN)
#define RCC_APB2STR_USART1_RESET()         SET_BIT(RCC->APB2RSTR,RCC_APB2STR_USART1STREN)
#define RCC_APB2STR_SPI4_RESET()           SET_BIT(RCC->APB2RSTR,RCC_APB2STR_SPI4STREN)
#define RCC_APB2STR_TIM15_RESET()          SET_BIT(RCC->APB2RSTR,RCC_APB2STR_TIM15STREN)
#define RCC_APB2STR_TIM16_RESET()          SET_BIT(RCC->APB2RSTR,RCC_APB2STR_TIM16STREN)
#define RCC_APB2STR_TIM17_RESET()          SET_BIT(RCC->APB2RSTR,RCC_APB2STR_TIM17STREN)
#define RCC_APB2STR_TIM20_RESET()          SET_BIT(RCC->APB2RSTR,RCC_APB2STR_TIM20STREN)


/*
 * RCC_APB1STR Register Macros
 *
 */


#define RCC_APB1STR_TIM2_RESET()           SET_BIT(RCC->APB1RSTR,RCC_APB1STR_TIM2STREN)
#define RCC_APB1STR_TIM3_RESET()           SET_BIT(RCC->APB1RSTR,RCC_APB1STR_TIM3STREN)
#define RCC_APB1STR_TIM4_RESET()           SET_BIT(RCC->APB1RSTR,RCC_APB1STR_TIM4STREN)
#define RCC_APB1STR_TIM6_RESET()           SET_BIT(RCC->APB1RSTR,RCC_APB1STR_TIM6STREN)
#define RCC_APB1STR_TIM7_RESET()           SET_BIT(RCC->APB1RSTR,RCC_APB1STR_TIM7STREN)
#define RCC_APB1STR_WWDG_RESET()           SET_BIT(RCC->APB1RSTR,RCC_APB1STR_WWDGSTREN)
#define RCC_APB1STR_SPI2_RESET()           SET_BIT(RCC->APB1RSTR,RCC_APB1STR_SPI2STREN)
#define RCC_APB1STR_SPI3_RESET()           SET_BIT(RCC->APB1RSTR,RCC_APB1STR_SPI3STREN)
#define RCC_APB1STR_USART2_RESET()         SET_BIT(RCC->APB1RSTR,RCC_APB1STR_USART2STREN)
#define RCC_APB1STR_USART3_RESET()         SET_BIT(RCC->APB1RSTR,RCC_APB1STR_USART3STREN)
#define RCC_APB1STR_UART4_RESET()          SET_BIT(RCC->APB1RSTR,RCC_APB1STR_UART4STREN)
#define RCC_APB1STR_UART5_RESET()          SET_BIT(RCC->APB1RSTR,RCC_APB1STR_UART5STREN)
#define RCC_APB1STR_I2C1_RESET()           SET_BIT(RCC->APB1RSTR,RCC_APB1STR_I2C1STREN)
#define RCC_APB1STR_I2C2_RESET()           SET_BIT(RCC->APB1RSTR,RCC_APB1STR_I2C2STREN)
#define RCC_APB1STR_USB_RESET()            SET_BIT(RCC->APB1RSTR,RCC_APB1STR_USBSTREN)
#define RCC_APB1STR_CAN_RESET()            SET_BIT(RCC->APB1RSTR,RCC_APB1STR_CANSTREN)
#define RCC_APB1STR_DAC2_RESET()           SET_BIT(RCC->APB1RSTR,RCC_APB1STR_DAC2STREN)
#define RCC_APB1STR_PWR_RESET()            SET_BIT(RCC->APB1RSTR,RCC_APB1STR_PWRSTREN)
#define RCC_APB1STR_DAC1_RESET()           SET_BIT(RCC->APB1RSTR,RCC_APB1STR_DAC1STREN)
#define RCC_APB1STR_I2C3_RESET()           SET_BIT(RCC->APB1RSTR,RCC_APB1STR_I2C3STREN)


/*
 * RCC_AHBENR Register Macros
 *
 */


#define RCC_DMA1_CLCK_ENABLE()       SET_BIT(RCC->AHBENR,RCC_AHBENR_DMA1EN)
#define RCC_DMA1_CLCK_DISABLE()      CLEAR_BIT(RCC->AHBENR,RCC_AHBENR_DMA1EN)
#define RCC_DMA1_CLKC_READ()         do{uint32_t tempReg=0;                               \
                                     tempReg=READ_BIT(RCC->AHBENR,RCC_AHBENR_DMA1EN); \
                                     UNUSED(tempReg);                                  \
                                     }while(0)

#define RCC_DMA2_CLCK_ENABLE()       SET_BIT(RCC->AHBENR,RCC_AHBENR_DMA2EN)
#define RCC_DMA2_CLCK_DISABLE()      CLEAR_BIT(RCC->AHBENR,RCC_AHBENR_DMA2EN)
#define RCC_DMA2_CLKC_READ()         do{uint32_t tempReg=0;                               \
                                     tempReg=READ_BIT(RCC->AHBENR,RCC_AHBENR_DMA2EN); \
                                     UNUSED(tempReg);                                  \
                                     }while(0)

#define RCC_SRAM_CLCK_ENABLE()       SET_BIT(RCC->AHBENR,RCC_AHBENR_SRAMEN)
#define RCC_SRAM_CLCK_DISABLE()      CLEAR_BIT(RCC->AHBENR,RCC_AHBENR_SRAMEN)
#define RCC_SRAM_CLKC_READ()         do{uint32_t tempReg=0;                               \
                                     tempReg=READ_BIT(RCC->AHBENR,RCC_AHBENR_SRAMEN); \
                                     UNUSED(tempReg);                                  \
                                     }while(0)

#define RCC_FLIT_CLCK_ENABLE()       SET_BIT(RCC->AHBENR,RCC_AHBENR_FLITEN)
#define RCC_FLIT_CLCK_DISABLE()      CLEAR_BIT(RCC->AHBENR,RCC_AHBENR_FLITEN)
#define RCC_FLIT_CLKC_READ()         do{uint32_t tempReg=0;                               \
                                     tempReg=READ_BIT(RCC->AHBENR,RCC_AHBENR_FLITEN); \
                                     UNUSED(tempReg);                                  \
                                     }while(0)

#define RCC_CRC_CLCK_ENABLE()        SET_BIT(RCC->AHBENR,RCC_AHBENR_CRCEN)
#define RCC_CRC_CLCK_DISABLE()       CLEAR_BIT(RCC->AHBENR,RCC_AHBENR_CRCEN)
#define RCC_CRC_CLKC_READ()          do{uint32_t tempReg=0;                               \
                                      tempReg=READ_BIT(RCC->AHBENR,RCC_AHBENR_CRCEN); \
                                      UNUSED(tempReg);                                  \
                                      }while(0)

#define RCC_GPIOA_CLKC_ENABLE()       SET_BIT(RCC->AHBENR,RCC_AHBENR_GPIOAEN)
#define RCC_GPIOA_CLKC_DISABLE()      CLEAR_BIT(RCC->AHBENR,RCC_AHBENR_GPIOAEN)
#define RCC_GPIOA_CLKC_READ()         do{uint32_t tempReg=0;                               \
                                      tempReg=READ_BIT(RCC->AHBENR,RCC_AHBENR_GPIOAEN); \
                                      UNUSED(tempReg);                                  \
                                      }while(0)

#define RCC_GPIOB_CLCK_ENABLE()       SET_BIT(RCC->AHBENR,RCC_AHBENR_GPIOBEN)
#define RCC_GPIOB_CLCK_DISABLE()      CLEAR_BIT(RCC->AHBENR,RCC_AHBENR_GPIOBEN)
#define RCC_GPIOB_CLKC_READ()         do{uint32_t tempReg=0;                               \
                                      tempReg=READ_BIT(RCC->AHBENR,RCC_AHBENR_GPIOBEN); \
                                      UNUSED(tempReg);                                  \
                                      }while(0)

#define RCC_GPIOC_CLCK_ENABLE()       SET_BIT(RCC->AHBENR,RCC_AHBENR_GPIOCEN)
#define RCC_GPIOC_CLCK_DISABLE()      CLEAR_BIT(RCC->AHBENR,RCC_AHBENR_GPIOCEN)
#define RCC_GPIOC_CLKC_READ()         do{uint32_t tempReg=0;                               \
                                      tempReg=READ_BIT(RCC->AHBENR,RCC_AHBENR_GPIOCEN); \
                                      UNUSED(tempReg);                                  \
                                      }while(0)

#define RCC_GPIOD_CLCK_ENABLE()       SET_BIT(RCC->AHBENR,RCC_AHBENR_GPIODEN)
#define RCC_GPIOD_CLCK_DISABLE()      CLEAR_BIT(RCC->AHBENR,RCC_AHBENR_GPIODEN)
#define RCC_GPIOD_CLKC_READ()         do{uint32_t tempReg=0;                               \
                                      tempReg=READ_BIT(RCC->AHBENR,RCC_AHBENR_GPIODEN); \
                                      UNUSED(tempReg);                                  \
                                      }while(0)

#define RCC_GPIOE_CLCK_ENABLE()       SET_BIT(RCC->AHBENR,RCC_AHBENR_GPIOEEN)
#define RCC_GPIOE_CLCK_DISABLE()      CLEAR_BIT(RCC->AHBENR,RCC_AHBENR_GPIOEEN)
#define RCC_GPIOE_CLKC_READ()         do{uint32_t tempReg=0;                               \
                                      tempReg=READ_BIT(RCC->AHBENR,RCC_AHBENR_GPIOEEN); \
                                      UNUSED(tempReg);                                  \
                                      }while(0)

#define RCC_GPIOF_CLCK_ENABLE()       SET_BIT(RCC->AHBENR,RCC_AHBENR_GPIOFEN)
#define RCC_GPIOF_CLCK_DISABLE()      CLEAR_BIT(RCC->AHBENR,RCC_AHBENR_GPIOFEN)
#define RCC_GPIOF_CLKC_READ()         do{uint32_t tempReg=0;                               \
                                      tempReg=READ_BIT(RCC->AHBENR,RCC_AHBENR_GPIOFEN); \
                                      UNUSED(tempReg);                                  \
                                      }while(0)

#define RCC_TSC_CLCK_ENABLE()         SET_BIT(RCC->AHBENR,RCC_AHBENR_TSCEN)
#define RCC_TSC_CLCK_DISABLE()        CLEAR_BIT(RCC->AHBENR,RCC_AHBENR_TSCEN)
#define RCC_TSC_CLKC_READ()           do{uint32_t tempReg=0;                               \
                                      tempReg=READ_BIT(RCC->AHBENR,RCC_AHBENR_TSCEN); \
                                      UNUSED(tempReg);                                  \
                                      }while(0)

#define RCC_ADC12_CLCK_ENABLE()       SET_BIT(RCC->AHBENR,RCC_AHBENR_ADC12EN)
#define RCC_ADC12_CLCK_DISABLE()      CLEAR_BIT(RCC->AHBENR,RCC_AHBENR_ADC12EN)
#define RCC_ADC12_CLKC_READ()         do{uint32_t tempReg=0;                               \
                                      tempReg=READ_BIT(RCC->AHBENR,RCC_AHBENR_ADC12EN); \
                                      UNUSED(tempReg);                                  \
                                      }while(0)

#define RCC_ADC34_CLCK_ENABLE()       SET_BIT(RCC->AHBENR,RCC_AHBENR_ADC34EN)
#define RCC_ADC34_CLCK_DISABLE()      CLEAR_BIT(RCC->AHBENR,RCC_AHBENR_ADC34EN)
#define RCC_ADC34_CLKC_READ()         do{uint32_t tempReg=0;                               \
                                      tempReg=READ_BIT(RCC->AHBENR,RCC_AHBENR_ADC34EN); \
                                      UNUSED(tempReg);                                  \
                                      }while(0)

/*
 * RCC_APB2ENR Register Macros
 *
 */


#define RCC_APB2ENR_SYSCFGR_ENABLE()        SET_BIT(RCC->APB2ENR,RCC_APB2ENR_SYSCFGEN)
#define RCC_APB2ENR_SYSCFGR_DISABLE()       CLEAR_BIT(RCC->APB2ENR,RCC_APB2ENR_SYSCFGEN)

#define RCC_APB2ENR_TIM1_ENABLE()           SET_BIT(RCC->APB2ENR,RCC_APB2ENR_TIM1EN)
#define RCC_APB2ENR_TIM1_DISABLE()          CLEAR_BIT(RCC->APB2ENR,RCC_APB2ENR_TIM1EN)

#define RCC_APB2ENR_SPI1_ENABLE()           SET_BIT(RCC->APB2ENR,RCC_APB2ENR_SPI1EN)
#define RCC_APB2ENR_SPI1_DISABLE()          CLEAR_BIT(RCC->APB2ENR,RCC_APB2ENR_SPI1EN)

#define RCC_APB2ENR_TIM8_ENABLE()           SET_BIT(RCC->APB2ENR,RCC_APB2ENR_TIM8EN)
#define RCC_APB2ENR_TIM8_DISABLE()          CLEAR_BIT(RCC->APB2ENR,RCC_APB2ENR_TIM8EN)

#define RCC_APB2ENR_USART1_ENABLE()         SET_BIT(RCC->APB2ENR,RCC_APB2ENR_USART1EN)
#define RCC_APB2ENR_USART1_DISABLE()        CLEAR_BIT(RCC->APB2ENR,RCC_APB2ENR_USART1EN)

#define RCC_APB2ENR_SPI4_ENABLE()           SET_BIT(RCC->APB2ENR,RCC_APB2ENR_SPI4EN)
#define RCC_APB2ENR_SPI4_DISABLE()          CLEAR_BIT(RCC->APB2ENR,RCC_APB2ENR_SPI4EN)

#define RCC_APB2ENR_TIM15_ENABLE()          SET_BIT(RCC->APB2ENR,RCC_APB2ENR_TIM15EN)
#define RCC_APB2ENR_TIM15_DISABLE()         CLEAR_BIT(RCC->APB2ENR,RCC_APB2ENR_TIM15EN)

#define RCC_APB2ENR_TIM16_ENABLE()          SET_BIT(RCC->APB2ENR,RCC_APB2ENR_TIM16EN)
#define RCC_APB2ENR_TIM16_DISABLE()         CLEAR_BIT(RCC->APB2ENR,RCC_APB2ENR_TIM16EN)

#define RCC_APB2ENR_TIM17_ENABLE()          SET_BIT(RCC->APB2ENR,RCC_APB2ENR_TIM17EN)
#define RCC_APB2ENR_TIM17_DISABLE()         CLEAR_BIT(RCC->APB2ENR,RCC_APB2ENR_TIM17EN)

#define RCC_APB2ENR_TIM20_ENABLE()          SET_BIT(RCC->APB2ENR,RCC_APB2ENR_TIM20EN)
#define RCC_APB2ENR_TIM20_DISABLE()         CLEAR_BIT(RCC->APB2ENR,RCC_APB2ENR_TIM20EN)


/*
 * RCC_APB1ENR Register Macros
 *
 */


#define RCC_APB1ENR_TIM2_ENABLE()         SET_BIT(RCC->APB1ENR,RCC_APB1ENR_TIM2EN)
#define RCC_APB1ENR_TIM2_DISABLE()        CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_TIM2EN)

#define RCC_APB1ENR_TIM3_ENABLE()         SET_BIT(RCC->APB1ENR,RCC_APB1ENR_TIM3EN)
#define RCC_APB1ENR_TIM3_DISABLE()        CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_TIM3EN)

#define RCC_APB1ENR_TIM4_ENABLE()         SET_BIT(RCC->APB1ENR,RCC_APB1ENR_TIM4EN)
#define RCC_APB1ENR_TIM4_DISABLE()        CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_TIM4EN)

#define RCC_APB1ENR_TIM6_ENABLE()         SET_BIT(RCC->APB1ENR,RCC_APB1ENR_TIM6EN)
#define RCC_APB1ENR_TIM6_DISABLE()        CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_TIM6EN)

#define RCC_APB1ENR_TIM7_ENABLE()         SET_BIT(RCC->APB1ENR,RCC_APB1ENR_TIM7EN)
#define RCC_APB1ENR_TIM7_DISABLE()        CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_TIM7EN)

#define RCC_APB1ENR_WWDG_ENABLE()         SET_BIT(RCC->APB1ENR,RCC_APB1ENR_WWDGEN)
#define RCC_APB1ENR_WWDG_DISABLE()        CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_WWDGEN)

#define RCC_APB1ENR_SPI2_ENABLE()         SET_BIT(RCC->APB1ENR,RCC_APB1ENR_SPI2EN)
#define RCC_APB1ENR_SPI2_DISABLE()        CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_SPI2EN)

#define RCC_APB1ENR_SPI3_ENABLE()         SET_BIT(RCC->APB1ENR,RCC_APB1ENR_SPI3EN)
#define RCC_APB1ENR_SPI3_DISABLE()        CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_SPI3EN)

#define RCC_APB1ENR_USART2_ENABLE()       SET_BIT(RCC->APB1ENR,RCC_APB1ENR_USART2EN)
#define RCC_APB1ENR_USART2_DISABLE()      CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_USART2EN)

#define RCC_APB1ENR_USART3_ENABLE()       SET_BIT(RCC->APB1ENR,RCC_APB1ENR_USART3EN)
#define RCC_APB1ENR_USART3_DISABLE()      CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_USART3EN)

#define RCC_APB1ENR_UART4_ENABLE()        SET_BIT(RCC->APB1ENR,RCC_APB1ENR_UART4EN)
#define RCC_APB1ENR_UART4_DISABLE()       CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_UART4EN)

#define RCC_APB1ENR_UART5_ENABLE()        SET_BIT(RCC->APB1ENR,RCC_APB1ENR_UART5EN)
#define RCC_APB1ENR_UART5_DISABLE()       CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_UART5EN)

#define RCC_APB1ENR_I2C1_ENABLE()         SET_BIT(RCC->APB1ENR,RCC_APB1ENR_I2C1EN)
#define RCC_APB1ENR_I2C1_DISABLE()        CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_I2C1EN)

#define RCC_APB1ENR_I2C2_ENABLE()         SET_BIT(RCC->APB1ENR,RCC_APB1ENR_I2C2EN)
#define RCC_APB1ENR_I2C2_DISABLE()        CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_I2C2EN)

#define RCC_APB1ENR_USB_ENABLE()          SET_BIT(RCC->APB1ENR,RCC_APB1ENR_USBEN)
#define RCC_APB1ENR_USB_DISABLE()         CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_USBEN)

#define RCC_APB1ENR_CAN_ENABLE()          SET_BIT(RCC->APB1ENR,RCC_APB1ENR_CANEN)
#define RCC_APB1ENR_CAN_DISABLE()         CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_CANEN)

#define RCC_APB1ENR_DAC2_ENABLE()         SET_BIT(RCC->APB1ENR,RCC_APB1ENR_DAC2EN)
#define RCC_APB1ENR_DAC2_DISABLE()        CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_DAC2EN)

#define RCC_APB1ENR_PWR_ENABLE()          SET_BIT(RCC->APB1ENR,RCC_APB1ENR_PWREN)
#define RCC_APB1ENR_PWR_DISABLE()         CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_PWREN)

#define RCC_APB1ENR_DAC1_ENABLE()         SET_BIT(RCC->APB1ENR,RCC_APB1ENR_DAC1EN)
#define RCC_APB1ENR_DAC1_DISABLE()        CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_DAC1EN)

#define RCC_APB1ENR_I2C3_ENABLE()         SET_BIT(RCC->APB1ENR,RCC_APB1ENR_I2C3EN)
#define RCC_APB1ENR_I2C3_DISABLE()        CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_I2C3EN)


/*
 * @def_group RCC_BDCR_LSEDRV
 *
 */


#define RCC_BDCR_LSEDRV_L            (0x00U)
#define RCC_BDCR_LSEDRV_MH           (0x01U)
#define RCC_BDCR_LSEDRV_ML           (0x02U)
#define RCC_BDCR_LSEDRV_H            (0x03U)


/*
 * @def_group RCC_BDCR_RTCSEL
 *
 */


#define RCC_BDCR_RTCSEL_NOCLK        (0x00U)
#define RCC_BDCR_RTCSEL_LSE          (0x01U)
#define RCC_BDCR_RTCSEL_LSI          (0x02U)
#define RCC_BDCR_RTCSEL_HSE          (0x03U)


/*
 * RCC_BDCR Register Macros
 *
 */


#define RCC_BDCR_LSE_ENABLE()              SET_BIT(RCC->RCCBDCR,RCC_BDCR_LSEONEN)
#define RCC_BDCR_LSE_DISABLE()             CLEAR_BIT(RCC->RCCBDCR,RCC_BDCR_LSEONEN)

#define RCC_BDCR_LSEBYP_ENABLE()           SET_BIT(RCC->RCCBDCR,RCC_BDCR_LSEBYPEN)
#define RCC_BDCR_LSEBYP_DISABLE()          CLEAR_BIT(RCC->RCCBDCR,RCC_BDCR_LSEBYPEN)


#define RCC_BDCR_LSEDRV_L_ENABLE()         SET_BIT(RCC->RCCBDCR,RCC_BDCR_LSEDRV_LEN)
#define RCC_BDCR_LSEDRV_MH_ENABLE()        SET_BIT(RCC->RCCBDCR,RCC_BDCR_LSEDRV_MHEN)
#define RCC_BDCR_LSEDRV_ML_ENABLE()        SET_BIT(RCC->RCCBDCR,RCC_BDCR_LSEDRV_MLEN)
#define RCC_BDCR_LSEDRV_H_ENABLE()         SET_BIT(RCC->RCCBDCR,RCC_BDCR_LSEDRV_HEN)

#define RCC_BDCR_RTCSEL_NOCLK_ENABLE()     SET_BIT(RCC->RCCBDCR,RCC_BDCR_RTCSEL_NOCLKEN)
#define RCC_BDCR_RTCSEL_LSE_ENABLE()       SET_BIT(RCC->RCCBDCR,RCC_BDCR_RTCSEL_LSEEN)
#define RCC_BDCR_RTCSEL_LSI_ENABLE()       SET_BIT(RCC->RCCBDCR,RCC_BDCR_RTCSEL_LSIEN)
#define RCC_BDCR_RTCSEL_HSE_ENABLE()       SET_BIT(RCC->RCCBDCR,RCC_BDCR_RTCSEL_HSEEN)

#define RCC_BDCR_RTC_ENABLE()              SET_BIT(RCC->RCCBDCR,RCC_BDCR_RTCENEN)
#define RCC_BDCR_RTC_DISABLE()             CLEAR_BIT(RCC->RCCBDCR,RCC_BDCR_RTCENEN)

#define RCC_BDCR_BDRST_ENABLE()            SET_BIT(RCC->RCCBDCR,RCC_BDCR_BDRSTEN)
#define RCC_BDCR_BDRST_DISABLE()           CLEAR_BIT(RCC->RCCBDCR,RCC_BDCR_BDRSTEN)


/*
 * RCC_AHBSTR Register Macros
 *
 */


#define RCC_AHBRSTR_FMCR_RESET()            SET_BIT(RCC->AHBRSTR,RCC_AHBSTR_FMCRSTEN)
#define RCC_AHBRSTR_IOPA_RESET()            SET_BIT(RCC->AHBRSTR,RCC_AHBSTR_IOPARSTEN)
#define RCC_AHBRSTR_IOPB_RESET()            SET_BIT(RCC->AHBRSTR,RCC_AHBSTR_IOPBRSTEN)
#define RCC_AHBRSTR_IOPC_RESET()            SET_BIT(RCC->AHBRSTR,RCC_AHBSTR_IOPCRSTEN)
#define RCC_AHBRSTR_IOPD_RESET()            SET_BIT(RCC->AHBRSTR,RCC_AHBSTR_IOPDRSTEN)
#define RCC_AHBRSTR_IOPE_RESET()            SET_BIT(RCC->AHBRSTR,RCC_AHBSTR_IOPERSTEN)
#define RCC_AHBRSTR_IOPF_RESET()            SET_BIT(RCC->AHBRSTR,RCC_AHBSTR_IOPFRSTEN)
#define RCC_AHBRSTR_TSC_RESET()             SET_BIT(RCC->AHBRSTR,RCC_AHBSTR_TSCRSTEN)
#define RCC_AHBRSTR_ADC12_RESET()           SET_BIT(RCC->AHBRSTR,RCC_AHBSTR_ADC12RSTEN)
#define RCC_AHBRSTR_ADC34_RESET()           SET_BIT(RCC->AHBRSTR,RCC_AHBSTR_ADC34RSTEN)


/*
 * @def_group RCC_CFGR2_PREDIV
 *
 */


#define RCC_CFGR2_PREDIV__PLLDIV1           (0x00U)
#define RCC_CFGR2_PREDIV__PLLDIV2           (0x01U)
#define RCC_CFGR2_PREDIV__PLLDIV3           (0x02U)
#define RCC_CFGR2_PREDIV__PLLDIV4           (0x03U)
#define RCC_CFGR2_PREDIV__PLLDIV5           (0x04U)
#define RCC_CFGR2_PREDIV__PLLDIV6           (0x05U)
#define RCC_CFGR2_PREDIV__PLLDIV7           (0x06U)
#define RCC_CFGR2_PREDIV__PLLDIV8           (0x07U)
#define RCC_CFGR2_PREDIV__PLLDIV9           (0x08U)
#define RCC_CFGR2_PREDIV__PLLDIV10          (0x09U)
#define RCC_CFGR2_PREDIV__PLLDIV11          (0x0AU)
#define RCC_CFGR2_PREDIV__PLLDIV12          (0x0BU)
#define RCC_CFGR2_PREDIV__PLLDIV13          (0x0CU)
#define RCC_CFGR2_PREDIV__PLLDIV14          (0x0DU)
#define RCC_CFGR2_PREDIV__PLLDIV15          (0x0EU)
#define RCC_CFGR2_PREDIV__PLLDIV16          (0x0FU)


/*
 * @def_group RCC_CFGR2_ADC12PRES
 *
 */


#define RCC_CFGR2_ADC12PRES__PLLDIV1           (0x10U)
#define RCC_CFGR2_ADC12PRES__PLLDIV2           (0x11U)
#define RCC_CFGR2_ADC12PRES__PLLDIV4           (0x12U)
#define RCC_CFGR2_ADC12PRES__PLLDIV6           (0x13U)
#define RCC_CFGR2_ADC12PRES__PLLDIV8           (0x14U)
#define RCC_CFGR2_ADC12PRES__PLLDIV10          (0x15U)
#define RCC_CFGR2_ADC12PRES__PLLDIV12          (0x16U)
#define RCC_CFGR2_ADC12PRES__PLLDIV16          (0x17U)
#define RCC_CFGR2_ADC12PRES__PLLDIV32          (0x18U)
#define RCC_CFGR2_ADC12PRES__PLLDIV64          (0x19U)
#define RCC_CFGR2_ADC12PRES__PLLDIV128         (0x1AU)
#define RCC_CFGR2_ADC12PRES__PLLDIV256         (0x1BU)


/*
 * @def_group RCC_CFGR2_ADC34PRES
 *
 */


#define RCC_CFGR2_ADC34PRES__PLLDIV1           (0x10U)
#define RCC_CFGR2_ADC34PRES__PLLDIV2           (0x11U)
#define RCC_CFGR2_ADC34PRES__PLLDIV4           (0x12U)
#define RCC_CFGR2_ADC34PRES__PLLDIV6           (0x13U)
#define RCC_CFGR2_ADC34PRES__PLLDIV8           (0x14U)
#define RCC_CFGR2_ADC34PRES__PLLDIV10          (0x15U)
#define RCC_CFGR2_ADC34PRES__PLLDIV12          (0x16U)
#define RCC_CFGR2_ADC34PRES__PLLDIV16          (0x17U)
#define RCC_CFGR2_ADC34PRES__PLLDIV32          (0x18U)
#define RCC_CFGR2_ADC34PRES__PLLDIV64          (0x19U)
#define RCC_CFGR2_ADC34PRES__PLLDIV128         (0x1AU)
#define RCC_CFGR2_ADC34PRES__PLLDIV256         (0x1BU)


/*
 * RCC_CFGR2 Register Macros
 *
 */


#define RCC_CFGR2_PREDIV1_ENABLE()             SET_BIT(RCC->CFGR2,RCC_CFGR2_PREDIV1EN)
#define RCC_CFGR2_PREDIV2_ENABLE()             SET_BIT(RCC->CFGR2,RCC_CFGR2_PREDIV2EN)
#define RCC_CFGR2_PREDIV3_ENABLE()             SET_BIT(RCC->CFGR2,RCC_CFGR2_PREDIV3EN)
#define RCC_CFGR2_PREDIV4_ENABLE()             SET_BIT(RCC->CFGR2,RCC_CFGR2_PREDIV4EN)
#define RCC_CFGR2_PREDIV5_ENABLE()             SET_BIT(RCC->CFGR2,RCC_CFGR2_PREDIV5EN)
#define RCC_CFGR2_PREDIV6_ENABLE()             SET_BIT(RCC->CFGR2,RCC_CFGR2_PREDIV6EN)
#define RCC_CFGR2_PREDIV7_ENABLE()             SET_BIT(RCC->CFGR2,RCC_CFGR2_PREDIV7EN)
#define RCC_CFGR2_PREDIV8_ENABLE()             SET_BIT(RCC->CFGR2,RCC_CFGR2_PREDIV8EN)
#define RCC_CFGR2_PREDIV9_ENABLE()             SET_BIT(RCC->CFGR2,RCC_CFGR2_PREDIV9EN)
#define RCC_CFGR2_PREDIV10_ENABLE()            SET_BIT(RCC->CFGR2,RCC_CFGR2_PREDIV10EN)
#define RCC_CFGR2_PREDIV11_ENABLE()            SET_BIT(RCC->CFGR2,RCC_CFGR2_PREDIV11EN)
#define RCC_CFGR2_PREDIV12_ENABLE()            SET_BIT(RCC->CFGR2,RCC_CFGR2_PREDIV12EN)
#define RCC_CFGR2_PREDIV13_ENABLE()            SET_BIT(RCC->CFGR2,RCC_CFGR2_PREDIV13EN)
#define RCC_CFGR2_PREDIV14_ENABLE()            SET_BIT(RCC->CFGR2,RCC_CFGR2_PREDIV14EN)
#define RCC_CFGR2_PREDIV15_ENABLE()            SET_BIT(RCC->CFGR2,RCC_CFGR2_PREDIV15EN)
#define RCC_CFGR2_PREDIV16_ENABLE()            SET_BIT(RCC->CFGR2,RCC_CFGR2_PREDIV16EN)


#define RCC_CFGR2_ADC12_PRES1_ENABLE()         SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC12PRES1EN)
#define RCC_CFGR2_ADC12_PRES2_ENABLE()         SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC12PRES2EN)
#define RCC_CFGR2_ADC12_PRES4_ENABLE()         SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC12PRES4EN)
#define RCC_CFGR2_ADC12_PRES6_ENABLE()         SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC12PRES6EN)
#define RCC_CFGR2_ADC12_PRES8_ENABLE()         SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC12PRES8EN)
#define RCC_CFGR2_ADC12_PRES10_ENABLE()        SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC12PRES10EN)
#define RCC_CFGR2_ADC12_PRES12_ENABLE()        SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC12PRES12EN)
#define RCC_CFGR2_ADC12_PRES16_ENABLE()        SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC12PRES16EN)
#define RCC_CFGR2_ADC12_PRES32_ENABLE()        SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC12PRES18EN)
#define RCC_CFGR2_ADC12_PRES64_ENABLE()        SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC12PRES64EN)
#define RCC_CFGR2_ADC12_PRES128_ENABLE()       SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC12PRES128EN)
#define RCC_CFGR2_ADC12_PRES256_ENABLE()       SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC12PRES256EN)


#define RCC_CFGR2_ADC34_PRES1_ENABLE()         SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC34PRES1EN)
#define RCC_CFGR2_ADC34_PRES2_ENABLE()         SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC34PRES2EN)
#define RCC_CFGR2_ADC34_PRES4_ENABLE()         SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC34PRES4EN)
#define RCC_CFGR2_ADC34_PRES6_ENABLE()         SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC34PRES6EN)
#define RCC_CFGR2_ADC34_PRES8_ENABLE()         SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC34PRES8EN)
#define RCC_CFGR2_ADC34_PRES10_ENABLE()        SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC34PRES10EN)
#define RCC_CFGR2_ADC34_PRES12_ENABLE()        SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC34PRES12EN)
#define RCC_CFGR2_ADC34_PRES16_ENABLE()        SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC34PRES16EN)
#define RCC_CFGR2_ADC34_PRES32_ENABLE()        SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC34PRES32EN)
#define RCC_CFGR2_ADC34_PRES64_ENABLE()        SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC34PRES64EN)
#define RCC_CFGR2_ADC34_PRES128_ENABLE()       SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC34PRES128EN)
#define RCC_CFGR2_ADC34_PRES256_ENABLE()       SET_BIT(RCC->CFGR2,RCC_CFGR2_ADC34PRES256EN)


/*
 * @def_group RCC_CFGR3_USARTxSW
 *
 */

#define RCC_CFGR3_USART1SW_PCLK                (0x00U)
#define RCC_CFGR3_USART1SW_SYSCLK              (0x01U)
#define RCC_CFGR3_USART1SW_LSE                 (0x02U)
#define RCC_CFGR3_USART1SW_HSI                 (0x03U)

#define RCC_CFGR3_USART2SW_PCLK                (0x00U)
#define RCC_CFGR3_USART2SW_SYSCLK              (0x01U)
#define RCC_CFGR3_USART2SW_LSE                 (0x02U)
#define RCC_CFGR3_USART2SW_HSI                 (0x03U)

#define RCC_CFGR3_USART3SW_PCLK                (0x00U)
#define RCC_CFGR3_USART3SW_SYSCLK              (0x01U)
#define RCC_CFGR3_USART3SW_LSE                 (0x02U)
#define RCC_CFGR3_USART3SW_HSI                 (0x03U)


/*
 * @def_group RCC_CFGR3_UARTxSW
 *
 */


#define RCC_CFGR3_UART4SW_PCLK                (0x00U)
#define RCC_CFGR3_UART4SW_SYSCLK              (0x01U)
#define RCC_CFGR3_UART4SW_LSE                 (0x02U)
#define RCC_CFGR3_UART4SW_HSI                 (0x03U)

#define RCC_CFGR3_UART5SW_PCLK                (0x00U)
#define RCC_CFGR3_UART5SW_SYSCLK              (0x01U)
#define RCC_CFGR3_UART5SW_LSE                 (0x02U)
#define RCC_CFGR3_UART5SW_HSI                 (0x03U)


/*
 * RCC_CFGR3 Register Macros
 *
 */


#define RCC_CFGR3_USART1_PCLK_ENABLE()        SET_BIT(RCC->CFGR3,RCC_CFGR3_USART1SW_PCLKEN)
#define RCC_CFGR3_USART1_SYSCLK_ENABLE()      SET_BIT(RCC->CFGR3,RCC_CFGR3_USART1SW_SYSCLKEN)
#define RCC_CFGR3_USART1_LSE_ENABLE()         SET_BIT(RCC->CFGR3,RCC_CFGR3_USART1SW_LSEEN)
#define RCC_CFGR3_USART1_HSI_ENABLE()         SET_BIT(RCC->CFGR3,RCC_CFGR3_USART1SW_HSIEN)

#define RCC_CFGR3_I2C1_ENABLE()               SET_BIT(RCC->CFGR3,RCC_CFGR3_I2C1SWEN)
#define RCC_CFGR3_I2C2_ENABLE()               SET_BIT(RCC->CFGR3,RCC_CFGR3_I2C2SWEN)
#define RCC_CFGR3_I2C3_ENABLE()               SET_BIT(RCC->CFGR3,RCC_CFGR3_I2C3SWEN)

#define RCC_CFGR3_TIM1_ENABLE()               SET_BIT(RCC->CFGR3,RCC_CFGR3_TIM1SWEN)
#define RCC_CFGR3_TIM8_ENABLE()               SET_BIT(RCC->CFGR3,RCC_CFGR3_TIM8SWEN)
#define RCC_CFGR3_TIM15_ENABLE()              SET_BIT(RCC->CFGR3,RCC_CFGR3_TIM15SWEN)
#define RCC_CFGR3_TIM16_ENABLE()              SET_BIT(RCC->CFGR3,RCC_CFGR3_TIM16SWEN)
#define RCC_CFGR3_TIM17_ENABLE()              SET_BIT(RCC->CFGR3,RCC_CFGR3_TIM17SWEN)
#define RCC_CFGR3_TIM20_ENABLE()              SET_BIT(RCC->CFGR3,RCC_CFGR3_TIM20SWEN)

#define RCC_CFGR3_USART2_PCLK_ENABLE()        SET_BIT(RCC->CFGR3,RCC_CFGR3_USART2SW_PCLKEN)
#define RCC_CFGR3_USART2_SYSCLK_ENABLE()      SET_BIT(RCC->CFGR3,RCC_CFGR3_USART2SW_SYSCLKEN)
#define RCC_CFGR3_USART2_LSE_ENABLE()         SET_BIT(RCC->CFGR3,RCC_CFGR3_USART2SW_LSEEN)
#define RCC_CFGR3_USART2_HSI_ENABLE()         SET_BIT(RCC->CFGR3,RCC_CFGR3_USART2SW_HSIEN)

#define RCC_CFGR3_USART3_PCLK_ENABLE()        SET_BIT(RCC->CFGR3,RCC_CFGR3_USART3SW_PCLKEN)
#define RCC_CFGR3_USART3_SYSCLK_ENABLE()      SET_BIT(RCC->CFGR3,RCC_CFGR3_USART3SW_SYSCLKEN)
#define RCC_CFGR3_USART3_LSE_ENABLE()         SET_BIT(RCC->CFGR3,RCC_CFGR3_USART3SW_LSEEN)
#define RCC_CFGR3_USART3_HSI_ENABLE()         SET_BIT(RCC->CFGR3,RCC_CFGR3_USART3SW_HSIEN)

#define RCC_CFGR3_UART4_PCLK_ENABLE()         SET_BIT(RCC->CFGR3,RCC_CFGR3_UART4SW_PCLKEN)
#define RCC_CFGR3_UART4_SYSCLK_ENABLE()       SET_BIT(RCC->CFGR3,RCC_CFGR3_UART4SW_SYSCLKEN)
#define RCC_CFGR3_UART4_LSE_ENABLE()          SET_BIT(RCC->CFGR3,RCC_CFGR3_UART4SW_LSEEN)
#define RCC_CFGR3_UART4_HSI_ENABLE()          SET_BIT(RCC->CFGR3,RCC_CFGR3_UART4SW_HSIEN)

#define RCC_CFGR3_UART5_PCLK_ENABLE()         SET_BIT(RCC->CFGR3,RCC_CFGR3_UART5SW_PCLKEN)
#define RCC_CFGR3_UART5_SYSCLK_ENABLE()       SET_BIT(RCC->CFGR3,RCC_CFGR3_UART5SW_SYSCLKEN)
#define RCC_CFGR3_UART5_LSE_ENABLE()          SET_BIT(RCC->CFGR3,RCC_CFGR3_UART5SW_LSEEN)
#define RCC_CFGR3_UART5_HSI_ENABLE()          SET_BIT(RCC->CFGR3,RCC_CFGR3_UART5SW_HSIEN)

#define RCC_CFGR3_TIM2_HSI_ENABLE()           SET_BIT(RCC->CFGR3,RCC_CFGR3_TIM2SWEN)
#define RCC_CFGR3_TIM34_HSI_ENABLE()          SET_BIT(RCC->CFGR3,RCC_CFGR3_TIM34SWEN)




#endif /* INC_RCC_H_ */
